version: '2'
services:
  plamtop-pig-admin:
    image: pig/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  plamtop-pig-api:
    image: pig/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev